---
title: "My first R Markdown"
author: "Sanchita"
date: "8 May 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Download sleep study data

```{r}
library(readr)
sleep <-read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/lme4/sleepstudy.csv") # no spaces
head(sleep)
```

You can also embed plots, for example:


Plot the data by subject
```{r}
library(ggplot2)
ggplot(sleep, aes(x = Days, y = Reaction)) +
  geom_point() +
  geom_smooth() +
  scale_x_continuous(breaks = seq(0, 8, by = 2)) +
  facet_wrap(~ Subject)
```

Summary statistics by subject

```{r}
library(dplyr)
sleep %>%
  group_by(Subject) %>%
  summarise(mean(Reaction))
```
Mean-center reaction times and plot on a single axis
```{r}
sleep %>%
  group_by(Subject) %>%
  mutate(mean_centered_reaction = Reaction - mean(Reaction)) %>%
  ggplot(aes(x = Days, y = mean_centered_reaction,
             color = factor(Subject))) +
  geom_smooth(show.legend = FALSE, se = FALSE) +
  scale_x_continuous(breaks = seq( 0, 8, by = 2))
```


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
